### PR TITLE
Add feature: Run epages-docs in docker container for development.

### PR DESCRIPTION
**Pull request by dataduke**

### CODE REVIEW

**Comment by choffmeister** [comment]
Very nice. Will test this today (or maybe tomorrow) and then merge

**Comment by choffmeister** [comment]
If this works do u mind when I squash this together before merging?

**Comment by dataduke** [comment]
Thanks. I will improve this a bit by writing a CircleCI test and adding some lines to the entrypoint script. Then I don't mind doing squashing. Sure, why not. Might be finished by tomorrow morning - I guess. I will send you a notification.

**Comment by dataduke** [comment]
superseeded by https://github.com/ePages-de/epages-docs/pull/386

* I tested `alpine` as base image (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-ruby-alpine/Dockerfile.ruby) but this would enforce us to use experimental gems (http://stackoverflow.com/questions/32560047/dockerization-of-octopress-with-alpine-linux). So no deal here.

* I also investigated in using a proper user id (instead of root) for all commands (jekyll/bundler/rake services) run inside of the ruby docker container. The Dockerfile would look good (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-with-dedicated-user/Dockerfile.ruby). The entrypoint script would get messy and unsynchronized with the desired rake invocations... as the current Rakefile currently doesn't allow to brigde through the user id to the wrapped bundle nor jekyll commands (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-with-dedicated-user/_docker/ruby/docker-entrypoint.sh). So we should also not do this. I think for development the root user in docker should be sufficient and the Rakefile is already complex enough.

**Comment by dataduke** [comment]
@choffmeister
superseeded by https://github.com/ePages-de/epages-docs/pull/386

* I tested `alpine` as base image (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-ruby-alpine/Dockerfile.ruby) but this would enforce us to use experimental gems (http://stackoverflow.com/questions/32560047/dockerization-of-octopress-with-alpine-linux). So no deal here.

* I also investigated in using a proper user id (instead of root) for all commands (jekyll/bundler/rake services) run inside of the ruby docker container. The Dockerfile would look good (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-with-dedicated-user/Dockerfile.ruby). The entrypoint script would get messy and unsynchronized with the desired rake invocations... as the current Rakefile currently doesn't allow to brigde through the user id to the wrapped bundle nor jekyll commands (https://github.com/dataduke/epages-docs/blob/feature/run-in-docker-with-dedicated-user/_docker/ruby/docker-entrypoint.sh). So we should also not do this. I think for development the root user in docker should be sufficient and the Rakefile is already complex enough.

**Comment by choffmeister** [comment]
Ok. Sry totally forgit that I wanted to look into it... :(

**Pull request closed without merging**
