### PR TITLE
ready for review

### PR DESCRIPTION
**Pull request by dmoran-epages**

### CODE REVIEW

**Comment by BirgitBader** [comment]
@maletzke @steffimeier please give your feedback
@netzfisch @mingoscd would you also like to check that from the ruby perspective?

**Comment by netzfisch** [comment]
In generell I am fine - looks like a comprehensive comparison.

Although I didn't go into detail, @dmoran-epages might answer me or the reader, why I shouldn't us ruby-install vs. building from scratch?
Because in my repos I have to constantly switch up to ten different ruby-versions, every few weeks there comes a new one and compiling all this stuff is very tedious and time consuming! And actually I never heard of a ruby-pro doing so.
Probably it is more academic reason like Arch-Linux vs. Debian, Ubuntu, SuSE, etc,

But I can stand with you opinion, so probably you should explain in more detail, why that way!

**Comment by dmoran-epages** [comment]
Hi.

> why I shouldn't us ruby-install vs. building from scratch?

I thought I did do this but maybe I didnt make myself clear enough:

> This -is- theoretically the ideal solution

In practice there's a catch however

> You can install ruby fine with a tool like Rvm or ruby-install. However subsequently installing rails (as a gem) requires access to source files like ruby.h
If you install these via your OS (package manager) then you risk a version mismatch which may cause errors during the build (or worse, at runtime). So you need these header files anyways and the best way to get them is to download the source code for ruby.

I don't know why or if this is just problem with the current version of ruby-install (its been a problem for a few years however, as internet searches show) but it installs a ruby that itself needs ruby source files to install gems like rails. BUT the ruby version (installed by ruby-install) doesn't have (access to) its own copy thereof.
If you have the ruby.h and any other necessary source files globally available on your system (on mine they're in a package called "ruby-devel") then ruby-install will silently and happily use them. This will give rise to the version mismatch and unpredictable (ie the worst) behaviour.

The only way I could see of solving this issue (without affecting any system ruby) was to install ruby from source.

Also the time and effort needed to do so way not significantly greater than using ruby-install.

**Comment by BirgitBader** [comment]
@netzfisch Did that clarify your points?

**Comment by mingoscd** [comment]
:+1:

**Pull request merged**
