### PR TITLE
Improve side menu

### PR DESCRIPTION
**Pull request by thokari**
Following up on the feedback we gave on Friday regarding the new API-docs, I made a small improvement to the side menu.
It now highlights any active menu item (i.e. the one which points to the current URL).
The improvement is quite generic, and works also on the Blog pages, although it might not have been the prettiest way of implementing it. (The "proper" way possibly being hooking into the static site generation).

While doing this I also noticed that there is a duplicate entry in the API docs (Use Cases).

### CODE REVIEW

**Comment by thokari** [comment]
I just notice the failing tests and additional commits. Did I start of the wrong branch maybe?

**Comment by thokari** [comment]
Deployed here: http://teamred-11.vm-intern.epages.com:4000/apps/

**Comment by unaitxu** [comment]
Thanks a lot for the Improvement. There are two things that are not working (so far): 

* When clicking on [Use cases](http://teamred-11.vm-intern.epages.com:4000/apps/use-cases) two fields are selected.
* When clicking into [any specific call](http://teamred-11.vm-intern.epages.com:4000/apps/api-reference/get-shopid-orders-orderid), is not being selected.

So, if those issues are not fixed, when can't merge it. We'd love to have an improved side menu, but it has to be coherent.

**Comment by thokari** [comment]
@unaitxu Yes, I noticed the problem regarding Use Cases, like I mentioned in the description.
The reason for me to still merge it is that it actually is a bug in the side menu that just happens to go unnoticed when there is no highlighting. So while my change makes this bug more prominent, I would still consider it an improvement.
Regarding the "any specific call", well, the problem here is that these points are not present in the menu so there is nothing to highlight.
And highlighting the "category" (e.g. "Carts") might be misleading, because clicking it will lead to a different page.
I might still implement it, so someone else can get an impression of it.

**Comment by BirgitBader** [comment]
@thokari can you make a separate PR for the template warning fix as this is not related to the sidbar issue. Thank you 😉

**Comment by thokari** [comment]
@BirgitBader https://github.com/ePages-de/epages-docs/pull/790

**Pull request merged**
