### PR TITLE
Enable parallel tests of prod nginx and dev ruby container

### PR DESCRIPTION
**Pull request by dataduke**

### CODE REVIEW

**Comment by choffmeister** [comment]
So back. @dataduke just give a small hint here, if you are done and have squashed the commits (if feasible)

**Comment by dataduke** [comment]
@choffmeister thanks.
I think there is a bug in the image and the CI test didn't  do an exit 1 because the site was not reachable. So I fixed the PR CI test.

I think I already discovered the underlying issue. 

At the time of creating the dockerfile the default rake task (read default docker cmd) was: `bundle exec jekyll serve --host 0.0.0.0 --watch` which worked fine. This has changed within the last week, when the PR was ready but not merged. So by rebasing to the new master the default cmd of docker got implicity another cmd.. although it has not changed within the Dockerfile.. 

Will try to fix this now.

**Comment by dataduke** [comment]
@choffmeister https://github.com/ePages-de/epages-docs/commit/6124273cc4a65551cbb413f31b575538d451bf63 introduced the new rake behaviour

**Comment by dataduke** [comment]
@choffmeister finally works and squashed a bit: https://github.com/ePages-de/epages-docs/pull/412

**Pull request closed without merging**
