### PR TITLE
EPT-5 - Multilanguage Code

### PR DESCRIPTION
**Pull request by mingoscd**
Added ruby script in api resources

### CODE REVIEW

**Comment by BirgitBader** [comment]
@choffmeister please check and merge if okay

**Comment by BirgitBader** [comment]
@mingoscd please add a description to the commit, so that it's one can note more easily what has been done with this commit

**Comment by choffmeister** [comment]
There seems to be a `}` missing. Is this a bug in raml_parser?

epages-docs2

**Comment by choffmeister** [comment]
@mingoscd The code is fine. Just fix the missing closing curly brace and you can merge it.

**Comment by mingoscd** [comment]
@choffmeister The missing curly brace also affects the Javascript example in that specific case, in other POST calls this problem doesn't appear

**Comment by BirgitBader** [comment]
@choffmeister what about this PR? There's still an open question.

**Comment by choffmeister** [comment]
The generated snippets still have errors. Even though, the error might have been there already before (and hence are my fault), this should be fixed first before merging this.

**Comment by BirgitBader** [comment]
@mingoscd please take care of this, and then merge the PR, thanks.

**Comment by mingoscd** [comment]
@choffmeister bug solved with the new PR on the raml_parser https://github.com/ePages-de/raml_parser/pull/12

**Comment by BirgitBader** [comment]
@mingoscd can you take care of this PR please? If it is solved, then please close it. Thank you.

**Comment by choffmeister** [comment]
The bug should be solved with https://github.com/ePages-de/raml_parser/pull/13, right? So please deploy the raml_parser in a new version, use it here and I am fine with the PR.

**Pull request merged**
