### PR TITLE
EPNG-9365 make customer account api public

### PR DESCRIPTION
**Pull request by wschneider-epages**

### CODE REVIEW

**Review by lackova — CHANGES_REQUESTED** [review]
I'd rather keep one main `Customer API` and have a submenu for `Customers` and `Customer accounts`. (Similar to other `API`s.)

**Comment by dkluever22** [comment]
@lackova FYI: Waldemar, Alice and I had a meeting last Friday and we decided to go with Waldemars solution. The topics differ too much in our opinion. That's why we want to add a separate point for the Customer Account API.

@wschneider-epages: We would like to integrate Customer Accounts API at the same level as Customer API in the sidebar but there are two issues in doing so:

1. Since the content within the frame and the sidebar are organized separately and the content has already been published, it needs to be relocated, which leads to the second problem.
2. I'm not sure if I've understood everything correctly, but looking at the structure of the API again, I would assume that the content of the Customer Account API needs to be stored in a separate repository to allow the Customer Account API to be on the same level as the Customer API in the sidebar. Can you confirm this? And if so, can you help me with this issue as I don't know how to do it. :see_no_evil:

**Comment by dkluever22** [comment]
Before Waldemar's changes can be implemented, [Task XYZ](https://epages.atlassian.net/browse/EPT-2200) needs to be completed. However, according to Christian, this may take a while.
In order to make the additional endpoints, which have already been published in the public documentation, also visible in the sidebar, I will take care of a temporary work around.
Waldemar's suggestion for the integration of the endpoints remains the preferred solution, which will be implemented as soon as possible.

**Comment by dkluever22** [comment]
@wschneider-epages As we worked on a solution for displaying the Customer Account contents separately and therefore needed to adjust the sidebar once more including the links the sidebar refers to (see PRs https://github.com/ePages-de/epages-docs/pull/1246 and https://github.com/ePages-de/ng-customer/pull/260) it probably would be best to close this PR. That way we could avoid conflicts between PR #1246 and this one.

**Comment by dkluever22** [comment]
PR has been closed because the task was completed via another PR

**Pull request closed without merging**
