### PR TITLE
Update events.md

### PR DESCRIPTION
**Pull request by depoulo**
see https://github.com/ePages-de/epages-ui/pull/4152#issuecomment-1044536321

### CODE REVIEW

**Review by lspalek — APPROVED** [review]

**Comment by depoulo** [comment]
@ePages-de/team-emerald do you have merge rights? Because we don't.

**Comment by ywolpers** [comment]
> @ePages-de/team-emerald do you have merge rights? Because we don't.

Looks like you do :D

**Comment by depoulo** [comment]
I did, but only temporarily.

**Comment by depoulo** [comment]
I did, but only temporarily.

**Comment by depoulo** [comment]
I did, but only temporarily.

**Pull request merged**
